### ISSUE TITLE
"Inconsistent ontology"

### ISSUE THREAD

**Issue by gherson** [AceWiki/AceWiki#23]
After loading sample data through manual interaction with AceWiki and restarting AceWiki, I was surprised to see all queries in a particular AceWiki instance unresponsive.  The command line that had launched AceWiki was showing

    2016-04-10 22:01:40.194:INFO::Started SelectChannelConnector@0.0.0.0:9077 STARTING
    Exception in thread "Thread-12" org.semanticweb.owlapi.reasoner.InconsistentOntologyException:     **Inconsistent ontology**
            at org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Unknown Source)
            at org.semanticweb.HermiT.Reasoner.checkPreConditions(Unknown Source)
    . . .

All the data of the instance had been entered via the preditor.  
I was able to clear the error by retracting all assertions, restarting AceWiki (all queries then returned "(no answer found)"), and reasserting them one by one.  When assertion "The current week is Week 12." was reached, AceWiki refused to re-assert, instead showing "The sentence is in conflict with the current knowledge. For that reason, it cannot be added to the knowledge base."

How was I able to enter a contradiction via the preditor?  And, if easy to find, what are the assertions in conflict?  thank you.

Attached is the .acewikidata export of the instance.

[current week prob.acewikidata.txt](https://github.com/AceWiki/AceWiki/files/213578/current.week.prob.acewikidata.txt)

**Comment by gherson** [comment]
Starting over in a fresh acewiki instance and ontology, I was able to define sentence "The current week is Week 12" where "current week" and "Week 12" are proper names.  
I then created noun "week".  Attempting to create sentence "Week 12 is a week." or "The current week is a week." hangs AceWiki.  A bug, no?

**Comment by gherson** [comment]
If I then create a 4th word, "Week 11", I cannot add sentence "Week 11 is a week": I get "The sentence is in conflict with the current knowledge."  What could possibly conflict, since the words "Week 11" and "week" have no other mention?

**Comment by gherson** [comment]
Please help!  have a deadline and haven't been able to get past the original problem, only confirm it.  I can reproduce it by loading an acewikidata file about the same as the attached.  Then in Acewiki I add proper name "current week" and sentence "The current week is Week 12", and confirm that queries are working.  I then stop and start AceWiki.  AceWiki starts w/o the ability to reason in this instance: all queries are blank and the command line is showing

    2016-04-16 19:41:55.396:INFO::Started SelectChannelConnector@0.0.0.0:9077 STARTING
    Exception in thread "Thread-12" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology

**Comment by tkuhn** [comment]
Yes, seems to be a bug. This is probably related to the fact that AceWiki applies the unique name assumption by adding an OWLDifferentIndividualsAxiom to make all individuals distinct: https://github.com/AceWiki/AceWiki/blob/master/src/ch/uzh/ifi/attempto/acewiki/owl/AceWikiOWLReasoner.java#L203

Statements of the form "P1 is P2" where P1 and P2 are both proper names are therefore inconsistent my themselves. Probably this bug is due to AceWiki not properly checking this self-contradiction... Commenting out the line above will probably solve the problem (but you might get other unexpected effects due to individuals with different names being considered the same).

**Comment by gherson** [comment]
Ok, thanks.  Determined that a few hours before your comment by substituting Pellet for HermiT and seeing explanation "Reason for inconsistency: [...] An individual is sameAs and differentFrom another individual at the same time".  Error messages are great for troubleshooting.

Before I try commenting out that line 203, can you briefly say how important you think the UNA is for AceWiki and if you think I should leave the line as is?

**Comment by tkuhn** [comment]
You might get some unexpected answers to your questions (or unexpected non-answers), and sentences that seem inconsistent might not be flagged as such, that's all. Other than that, nothing should break. It will probably be appartent in particular when you are using quantifiers like "at most", "at least", "exactly", etc. If you don't use these numerical quantifiers, the negative effects might be very unfrequent.

For example, if you have the statements "John knows exactly 1 person. Bill is a person. Mary is a person.", and then you add "John knows Bill. John knows Mary." no inconsistency is raised. The reasoner then just infers that Bill = Mary!

**Comment by gherson** [comment]
Great answer, thanks.  
I think I'd prefer the middle ground of the reasoner not inferring names to be synonyms unless explicitly told "A is B". 
I made "current week" a noun instead of proper name then left the UNA in place for now as sentences "Week 12 is a current week.", "What takes place in a current week?" and "There is exactly 1 current week." work for me.
